### ISSUE TITLE
erors

### ISSUE THREAD

**Issue by Mendel-light** [Syyreth/ModsAmongUs#12]
unfortunately there are a lot of bugs in the mod. We are constantly kicked out of the game for cheats. Rather, he writes that we have some kind of mistake and throws it out when, for example, a serial killer wants to kill someone. In general, any time someone other than the imposter makes a murder, he is immediately thrown out and banned in the room. The mod gives the impression of being unfinished. I made a ghost on an imposter for a ghoul, but it didn't work for me. I tried to make an emergency meeting when my friends turned to stone and all friends were thrown out of the game.

**Comment by qevcio** [comment]
It said do not use EU/NA/AS to play the game, use custom server - and you will not get ban

**Comment by Syyreth** [comment]
Thanks for responding for me, but yes, you have to use custom regions. The Ghoul role was a bug and that has been fixed :)
