### ISSUE TITLE
Issue with Chronos

### ISSUE THREAD

**Issue by Anchovys** [Syyreth/ModsAmongUs#16]
When Chronos uses his ability,sometimes it can just lag, so you can't use any administration tools,open doors or fix sabotages
![1 (1)](https://user-images.githubusercontent.com/82526094/119476432-df482980-bd6f-11eb-963e-afe2315c3d1d.jpg)

**Comment by Syyreth** [comment]
Hi, sorry for the late response! The way I coded Chronos caused a bit of lag, so I changed how it's added in, which should fix the lag issues, please let me know how that goes.
