### ISSUE TITLE
Spy problem

### ISSUE THREAD

**Issue by qevcio** [Syyreth/ModsAmongUs#19]
Spy just do not work, sometimes crewmate can see spy cameras, when spy using cameras and body/meeting reported, after meeting spy cant walk, he just seeing camera screen all the time

![image](https://user-images.githubusercontent.com/48392669/119689003-68c72c80-be40-11eb-82f0-de43a2130dd5.png)

**Comment by Syyreth** [comment]
Fixed this update :)
