### ISSUE TITLE
Ghoul

### ISSUE THREAD

**Issue by qevcio** [Syyreth/ModsAmongUs#23]
today we was playing with ghoul, on first releasse ghoul was fine, but now even if ghoul haunt impostor nothing happened,
the screen with scary ghoul on impostor creen do not come out, and ghoul losing his haunt button, impostor can continue the game

**Comment by Syyreth** [comment]
Sorry for the delay in the response, I was working on the Coven. Morpher and Spy need a small amount of work for their fix, but this bug should be fixed alongside the others. Thanks for reporting :)
