### ISSUE TITLE
bugs and suggestions

### ISSUE THREAD

**Issue by Nedys911** [Syyreth/ModsAmongUs#30]
medusa can win as a crew member if she turns everyone to stone and kills them. Also wanted to be able to Coven and traitors could be together, well, for example Spy + Necromancer. To be able to change the map without re-creating the lobby and custom colors and custom caps. Some people also like to make a mini-game out of the mod, and to do this, you can make the limit of people for a role greater than 1. I also noticed that the number of roles on the peaceful works crookedly because I put 6 peaceful 2 neutrals and 0 roles of the traitor to fall out Coven roles (put Coven roles) then often falls the usual traitor (even when there are 2 roles of the traitor) the usual Crewmate and 1 or neodnoy neutral roles. I would also like to be able to put a separate number of tasks for the phantom, because usually the tasks are set so that the game does not end quickly, and the phantom will not have time to do everything in 1 round. And if you do not do enough tasks, then the civilians will win in 1 round.

**Comment by Syyreth** [comment]
Thanks for your suggestions. Today I'm releasing an update for the latest version, and tomorrow I plan to release some custom colours and improvements to the coven roles which I've been working on the past few days (just need a little more time on them), after that I'll be more than happy to work on those and fix what needs to be fixed! Much appreciated :)
