### ISSUE TITLE
Issue w/customize

### ISSUE THREAD

**Issue by Anchovys** [Syyreth/ModsAmongUs#6]
I can't choose more or less crew roles than 5

**Comment by Anchovys** [comment]
Uploading 20210522-1421-02_OWad7bxT.mp4…

**Comment by Anchovys** [comment]
Also,there is a problem,like,when you choosing cooldown for Plaguebearer's pestillence or for guardian protect duration,it goes on a 10 sec on PB and on 30 sec on guardian

**Comment by Anchovys** [comment]
Also,do a customize for Plague, that we can choose how much players per round he can infect
)

**Comment by Syyreth** [comment]
These bugs should be fixed. For the attacking cooldowns, I keep the 10 the minimum as it follows the Impostor kill cooldowns. If you think it should be reduced, please let me know :)
