### ISSUE TITLE
Issues with neutral roles

### ISSUE THREAD

**Issue by Anchovys** [Syyreth/ModsAmongUs#7]
1.In some moments,for example,when you are a exectutioner,your role duplicates more time.I have no screen,sorry :(

2.Idk how it works,but when all the impostor dies,jester becomes impostor,that also works with executioner-jester
![1](https://user-images.githubusercontent.com/82526094/119234096-e394fc80-bb4d-11eb-8fc8-c57bb1570bf3.jpg)

**Comment by Syyreth** [comment]
Both of these bugs should be fixed in the next update :)
